using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;
using DnbCli.Models;

namespace DnbCli.Tools.GenerateResponseExamples;

internal static class Program
{
    /// <summary>
    /// Usage: GenerateResponseExamples &lt;output path&gt;
    /// Emits a static class with a Type→JSON-sample dictionary for every type
    /// registered on JsonContext via [JsonSerializable], skipping List/Dictionary
    /// helper registrations.
    /// </summary>
    public static int Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.Error.WriteLine("Usage: GenerateResponseExamples <output path>");
            return 1;
        }
        var outputPath = args[0];
        var types = DiscoverResponseTypes();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by tools/GenerateResponseExamples.");
        sb.AppendLine("//   Do not edit by hand — run `dotnet run --project tools/GenerateResponseExamples -- <path>`.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace DnbCli.Commands;");
        sb.AppendLine();
        sb.AppendLine("internal static class ResponseExamples");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<Type, string> Samples = new()");
        sb.AppendLine("    {");
        foreach (var type in types.OrderBy(t => t.FullName, StringComparer.Ordinal))
        {
            var sample = SampleJsonWalker.Render(type);
            sb.Append("        { typeof(").Append(FullTypeName(type)).AppendLine("),");
            sb.Append("          ").Append(Quote(sample)).AppendLine(" },");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static string For(Type type)");
        sb.AppendLine("        => Samples.TryGetValue(type, out var sample) ? sample : throw new KeyNotFoundException($\"No response example registered for {type.FullName}\");");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyDictionary<Type, string> All => Samples;");
        sb.AppendLine("}");

        var content = sb.ToString().Replace("\r\n", "\n");
        File.WriteAllText(outputPath, content);
        Console.WriteLine($"Wrote {types.Count} samples to {outputPath}");
        return 0;
    }

    private static List<Type> DiscoverResponseTypes()
    {
        // JsonSerializableAttribute.Type is only a constructor argument — use
        // CustomAttributeData to retrieve it at runtime.
        var attrData = typeof(JsonContext)
            .GetCustomAttributesData()
            .Where(d => d.AttributeType == typeof(JsonSerializableAttribute));
        return attrData
            .Select(d => (Type)d.ConstructorArguments[0].Value!)
            .Where(t => !IsCollectionHelperType(t))
            .ToList();
    }

    private static bool IsCollectionHelperType(Type t)
    {
        if (!t.IsGenericType) return false;
        var def = t.GetGenericTypeDefinition();
        return def == typeof(Dictionary<,>) || def == typeof(List<>);
    }

    private static string FullTypeName(Type t)
    {
        var ns = t.Namespace ?? "";
        return string.IsNullOrEmpty(ns) ? t.Name : $"{ns}.{t.Name}";
    }

    private static string Quote(string s)
        => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";
}
