using System.Collections.Concurrent;
using System.CommandLine;
using System.CommandLine.Help;
using System.CommandLine.Invocation;

namespace DnbCli.Commands;

public enum HelpSectionPosition { Top, Bottom }

public static class HelpExtensions
{
    private record Section(string Title, string[] Lines, HelpSectionPosition Position);

    private static readonly ConcurrentDictionary<Command, List<Section>> CommandSections = new();

    public static void AddHelpSection(this Command command, string title, params string[] lines)
        => command.AddHelpSection(title, HelpSectionPosition.Bottom, lines);

    public static void AddHelpSection(this Command command, string title, HelpSectionPosition position, params string[] lines)
    {
        var sections = CommandSections.GetOrAdd(command, _ => new List<Section>());
        sections.Add(new Section(title, lines, position));
    }

    public static void AddExamples(this Command command, params string[] examples)
        => command.AddHelpSection("Examples", HelpSectionPosition.Bottom, examples);

    /// <summary>
    /// Adds a "Response shape" section to the command's --help output, rendered
    /// from the JSON sample for <typeparamref name="T"/> generated by
    /// <c>tools/GenerateResponseExamples</c> (see <c>src/DnbCli/Commands/ResponseExamples.g.cs</c>).
    /// </summary>
    public static void AddResponseExample<T>(this Command command)
    {
        var json = ResponseExamples.For(typeof(T));
        command.AddHelpSection("Response shape", HelpSectionPosition.Bottom, json.Split('\n'));
    }

    public static void UseCustomHelpSections(this RootCommand root)
    {
        var helpOption = root.Options.OfType<HelpOption>().FirstOrDefault()
            ?? throw new InvalidOperationException("RootCommand has no HelpOption — cannot install CustomHelpAction.");
        if (helpOption.Action is not HelpAction defaultAction)
            throw new InvalidOperationException($"HelpOption.Action is {helpOption.Action?.GetType().Name ?? "null"}, expected HelpAction.");
        helpOption.Action = new CustomHelpAction(defaultAction);
    }

    private sealed class CustomHelpAction : SynchronousCommandLineAction
    {
        private readonly HelpAction _inner;
        public CustomHelpAction(HelpAction inner) { _inner = inner; }
        public override int Invoke(ParseResult parseResult)
        {
            var command = parseResult.CommandResult.Command;
            var output = parseResult.InvocationConfiguration.Output;
            WriteSections(command, output, HelpSectionPosition.Top);
            var rc = _inner.Invoke(parseResult);
            WriteSections(command, output, HelpSectionPosition.Bottom);
            return rc;
        }
    }

    private static void WriteSections(Command command, TextWriter output, HelpSectionPosition position)
    {
        if (!CommandSections.TryGetValue(command, out var sections)) return;
        foreach (var section in sections.Where(s => s.Position == position))
        {
            output.WriteLine($"{section.Title}:");
            foreach (var line in section.Lines)
                output.WriteLine($"  {line}");
            output.WriteLine();
        }
    }
}
