// <auto-generated>
//   Generated by tools/GenerateResponseExamples.
//   Do not edit by hand — run `dotnet run --project tools/GenerateResponseExamples -- <path>`.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace DnbCli.Commands;

internal static class ResponseExamples
{
    private static readonly Dictionary<Type, string> Samples = new()
    {
        { typeof(DnbCli.Models.Contributor),
          "{\n  \"Name\": \"<string>\",\n  \"Role\": \"<string>\",\n  \"RoleLabel\": null,\n  \"GndId\": null\n}" },
        { typeof(DnbCli.Models.DnbRecord),
          "{\n  \"DnbId\": \"<string>\",\n  \"Isbns\": [\n    \"<string>\"\n  ],\n  \"Title\": {\n    \"Main\": \"<string>\",\n    \"Subtitle\": null,\n    \"PartNumber\": null,\n    \"PartName\": null,\n    \"Uniform\": null,\n    \"StatementOfResponsibility\": null\n  },\n  \"Series\": [\n    {\n      \"Name\": \"<string>\",\n      \"Volume\": null\n    }\n  ],\n  \"Languages\": {\n    \"Publication\": [\n      \"<string>\"\n    ],\n    \"Original\": [\n      \"<string>\"\n    ]\n  },\n  \"Contributors\": [\n    {\n      \"Name\": \"<string>\",\n      \"Role\": \"<string>\",\n      \"RoleLabel\": null,\n      \"GndId\": null\n    }\n  ],\n  \"Publication\": {\n    \"Place\": null,\n    \"Publisher\": null,\n    \"Date\": null\n  },\n  \"Edition\": null,\n  \"Extent\": null,\n  \"Description\": null,\n  \"Genres\": [\n    \"<string>\"\n  ],\n  \"Subjects\": [\n    \"<string>\"\n  ],\n  \"Keywords\": [\n    \"<string>\"\n  ],\n  \"MarcSource\": \"<string>\"\n}" },
        { typeof(DnbCli.Models.Languages),
          "{\n  \"Publication\": [\n    \"<string>\"\n  ],\n  \"Original\": [\n    \"<string>\"\n  ]\n}" },
        { typeof(DnbCli.Models.Publication),
          "{\n  \"Place\": null,\n  \"Publisher\": null,\n  \"Date\": null\n}" },
        { typeof(DnbCli.Models.SearchEnvelope),
          "{\n  \"Query\": \"<string>\",\n  \"TotalResults\": 0,\n  \"ReturnedResults\": 0,\n  \"Page\": 0,\n  \"Limit\": 0,\n  \"Results\": [\n    {\n      \"DnbId\": \"<string>\",\n      \"Isbns\": [\n        \"<string>\"\n      ],\n      \"Title\": {\n        \"Main\": \"<string>\",\n        \"Subtitle\": null,\n        \"PartNumber\": null,\n        \"PartName\": null,\n        \"Uniform\": null,\n        \"StatementOfResponsibility\": null\n      },\n      \"Series\": [\n        {\n          \"Name\": \"<string>\",\n          \"Volume\": null\n        }\n      ],\n      \"Languages\": {\n        \"Publication\": [\n          \"<string>\"\n        ],\n        \"Original\": [\n          \"<string>\"\n        ]\n      },\n      \"Contributors\": [\n        {\n          \"Name\": \"<string>\",\n          \"Role\": \"<string>\",\n          \"RoleLabel\": null,\n          \"GndId\": null\n        }\n      ],\n      \"Publication\": {\n        \"Place\": null,\n        \"Publisher\": null,\n        \"Date\": null\n      },\n      \"Edition\": null,\n      \"Extent\": null,\n      \"Description\": null,\n      \"Genres\": [\n        \"<string>\"\n      ],\n      \"Subjects\": [\n        \"<string>\"\n      ],\n      \"Keywords\": [\n        \"<string>\"\n      ],\n      \"MarcSource\": \"<string>\"\n    }\n  ]\n}" },
        { typeof(DnbCli.Models.SeriesEntry),
          "{\n  \"Name\": \"<string>\",\n  \"Volume\": null\n}" },
        { typeof(DnbCli.Models.Title),
          "{\n  \"Main\": \"<string>\",\n  \"Subtitle\": null,\n  \"PartNumber\": null,\n  \"PartName\": null,\n  \"Uniform\": null,\n  \"StatementOfResponsibility\": null\n}" },
    };

    public static string For(Type type)
        => Samples.TryGetValue(type, out var sample) ? sample : throw new KeyNotFoundException($"No response example registered for {type.FullName}");

    public static IReadOnlyDictionary<Type, string> All => Samples;
}
