// <auto-generated>
//   Generated by tools/GenerateResponseExamples.
//   Do not edit by hand — run `dotnet run --project tools/GenerateResponseExamples -- <path>`.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace DnbCli.Commands;

internal static class ResponseExamples
{
    private static readonly Dictionary<Type, string> Samples = new()
    {
        { typeof(DnbCli.Models.Contributor),
          "{\n  \"name\": \"<string>\",\n  \"role\": \"<string>\",\n  \"roleLabel\": null,\n  \"gndId\": null\n}" },
        { typeof(DnbCli.Models.DnbRecord),
          "{\n  \"dnbId\": \"<string>\",\n  \"isbns\": [\n    \"<string>\"\n  ],\n  \"title\": {\n    \"main\": \"<string>\",\n    \"subtitle\": null,\n    \"partNumber\": null,\n    \"partName\": null,\n    \"uniform\": null,\n    \"statementOfResponsibility\": null\n  },\n  \"series\": [\n    {\n      \"name\": \"<string>\",\n      \"volume\": null\n    }\n  ],\n  \"languages\": {\n    \"publication\": [\n      \"<string>\"\n    ],\n    \"original\": [\n      \"<string>\"\n    ]\n  },\n  \"contributors\": [\n    {\n      \"name\": \"<string>\",\n      \"role\": \"<string>\",\n      \"roleLabel\": null,\n      \"gndId\": null\n    }\n  ],\n  \"publication\": {\n    \"place\": null,\n    \"publisher\": null,\n    \"date\": null\n  },\n  \"edition\": null,\n  \"extent\": null,\n  \"description\": null,\n  \"genres\": [\n    \"<string>\"\n  ],\n  \"subjects\": [\n    \"<string>\"\n  ],\n  \"keywords\": [\n    \"<string>\"\n  ],\n  \"marcSource\": \"<string>\"\n}" },
        { typeof(DnbCli.Models.Languages),
          "{\n  \"publication\": [\n    \"<string>\"\n  ],\n  \"original\": [\n    \"<string>\"\n  ]\n}" },
        { typeof(DnbCli.Models.Publication),
          "{\n  \"place\": null,\n  \"publisher\": null,\n  \"date\": null\n}" },
        { typeof(DnbCli.Models.SearchEnvelope),
          "{\n  \"query\": \"<string>\",\n  \"totalResults\": 0,\n  \"returnedResults\": 0,\n  \"page\": 0,\n  \"limit\": 0,\n  \"results\": [\n    {\n      \"dnbId\": \"<string>\",\n      \"isbns\": [\n        \"<string>\"\n      ],\n      \"title\": {\n        \"main\": \"<string>\",\n        \"subtitle\": null,\n        \"partNumber\": null,\n        \"partName\": null,\n        \"uniform\": null,\n        \"statementOfResponsibility\": null\n      },\n      \"series\": [\n        {\n          \"name\": \"<string>\",\n          \"volume\": null\n        }\n      ],\n      \"languages\": {\n        \"publication\": [\n          \"<string>\"\n        ],\n        \"original\": [\n          \"<string>\"\n        ]\n      },\n      \"contributors\": [\n        {\n          \"name\": \"<string>\",\n          \"role\": \"<string>\",\n          \"roleLabel\": null,\n          \"gndId\": null\n        }\n      ],\n      \"publication\": {\n        \"place\": null,\n        \"publisher\": null,\n        \"date\": null\n      },\n      \"edition\": null,\n      \"extent\": null,\n      \"description\": null,\n      \"genres\": [\n        \"<string>\"\n      ],\n      \"subjects\": [\n        \"<string>\"\n      ],\n      \"keywords\": [\n        \"<string>\"\n      ],\n      \"marcSource\": \"<string>\"\n    }\n  ]\n}" },
        { typeof(DnbCli.Models.SeriesEntry),
          "{\n  \"name\": \"<string>\",\n  \"volume\": null\n}" },
        { typeof(DnbCli.Models.Title),
          "{\n  \"main\": \"<string>\",\n  \"subtitle\": null,\n  \"partNumber\": null,\n  \"partName\": null,\n  \"uniform\": null,\n  \"statementOfResponsibility\": null\n}" },
    };

    public static string For(Type type)
        => Samples.TryGetValue(type, out var sample) ? sample : throw new KeyNotFoundException($"No response example registered for {type.FullName}");

    public static IReadOnlyDictionary<Type, string> All => Samples;
}
